jwt:
 secret: SxNAgsTkI1gseLfzLJNLH3P6UzsfASFSFASFffqwrAftewgfcGSywwryrjASDFGAgegasdfas
 expiration: 86400000

spring:
 data:
  mongodb:
   uri: mongodb://localhost:27017/springboot

aws:
 access_key_id: AKIA443IFD4NMPRRKD5Q
 secret_access_key: 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
 bucket: duarte-store
 region: sa-east-1