jwt:
 secret: SxNAgsTkI1gseLfzLJNLH3P6UzsfASFSFASFffqwrAftewgfcGSywwryrjASDFGAgegasdfas
 expiration: 86400000

spring:
 data:
  mongodb:
   uri: mongodb://vinidg:1234567@localhost:27017/duarte-store

aws:
 access_key_id: AKIA443IFD4NFAXDL7NJ
 secret_access_key: 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
 bucket: duarte-store
 region: sa-east-1