jwt:
 secret: SxNAgsTkI1gseLfzLJNLH3P6UzsfASFSFASFffqwrAftewgfcGSywwryrjASDFGAgegasdfas
 expiration: 86400000

spring:
 data:
  mongodb:
   uri: mongodb://vinidg:1234567@localhost:27017/duarte-store
#   uri: mongodb://localhost:27017/duarte-store

aws:
 access_key_id: 
 secret_access_key: 
 bucket: duarte-store
 region: sa-east-1